version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./www/:/var/www/
      - ./server/nginx1/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"

  php:
    build: .
    container_name: php-container
    environment:
      SERVER: '1'
    volumes:
      - ./www/:/var/www/
    ports:
      - "9001:9000"

  nginx2:
    image: nginx:latest
    container_name: nginx2-container
    volumes:
      - ./www/:/var/www/
      - ./server/nginx2/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
  
  php2:
    build: .
    container_name: php2-container
    environment:
      SERVER: '2'
    volumes:
      - ./www/:/var/www/
    ports:
      - "9002:9000"

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8090:80"
    depends_on:
      - mysql

volumes:
  database:
